# Generated by Django 4.2.14 on 2024-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='EMP101', max_length=255, unique=True),
        ),
    ]
